### PR TITLE
feat: Added formatter, values, path to MessageContext

### PR DESCRIPTION
**Pull request by fabis94**
If you use message function functionality, vue-i18n skips running the formatter on the results. I don't want this, I want to do some custom work in the message function, but then defer all of the formatting back to vue-i18n.

To make this possible I've added the formatter, all values and path into the MessageContext. I've added a test case for this as well.

### CODE REVIEW

**Comment by kazupon** [comment]
Thank you for your contribution.
I really appreciate your improvements to the message function!

The use-case for the message function, as mentioned in the documentation, is to support complex cases that cannot be handled by vue-i18n's formatter.
https://kazupon.github.io/vue-i18n/guide/messages.html#message-function

In PR, it is possible to specify a message, but it is difficult to extract this message as a resource. This makes it difficult to integrate it into the translation workflow with localization service.

This PR is great that can improve DX by supporting fomatter for message funciton, but it needs to solve the issue of integration with translation workflow.

There is a feature in vue-i18n that allows you to reference a message called `linked locale message`.
https://kazupon.github.io/vue-i18n/guide/messages.html#linked-locale-messages

We can solve the problem of integration with translation workflows by making it possible to reference messages in the message function.

However, at this time, we do not have a way to make the linked locale message available in the message function.
We need to make that available as well.

**Comment by fabis94** [comment]
@kazupon Am I understanding you correctly that there also needs to be a way to get the entire "messages" object inside the message function?

If so, I've added both `messages` and `locale` to the message context so that you can get any translated message this way.

**Comment by kazupon** [comment]
@fabis94 
Thank you for your updating!

Sorry for my poor explanation.

I add a `liked` function that can refer to a resource message in the context passed to the message functions as follows, and assumed the following usage:

```js
{
  hey: 'hey {x} {y}'.
  hello: (ctx) => ctx.formatter.interpolate(ctx.linked('hey'), ctx.values, ctx.path).join('')
}
```

**Comment by fabis94** [comment]
@kazupon I've updated the PR to also include the functionality you requested

**Review by kazupon — APPROVED** [review]
Sorry, late response

Thank you for your contribution!

I’ll merge your PR, but several props (`path`, `formatter`, messages`, and `locale`) of message context are not compatible for vue-i18n@v9.
I’ll write those to docs as a limitation

I appreciate your work!

**Comment by fabis94** [comment]
thank you @kazupon! any ideas when this will be released as a new version?

**Comment by kazupon** [comment]
I'm preparing for release now
https://github.com/kazupon/vue-i18n/pull/1322

**Comment by kazupon** [comment]
done!
https://github.com/kazupon/vue-i18n/releases/tag/v8.25.0

**Pull request merged**
