### PR TITLE
Extendable pluralization

### LINKED ISSUE #78: International pluralization
In English, pluralization looks simple: one and many. But it's not too simple for Russian language. And there is some other languages. 

`i18n` means Internationalization.

I suggest to use something better for pluralization into `$tc()`/`Vue.tc()`.

For example, [`smart-plurals`](https://www.npmjs.com/package/smart-plurals).

---

Now I using it with Vue like this:

``` js
// pluralize.js
import Vue from 'vue'
import smartPlurals from 'smart-plurals'
export default function pluralize(string, amount, lang) {
    string = Vue.t(string, lang).split(' | ')
    return smartPlurals.Plurals.getRule(lang)(amount, string)
}
```

So I can now write different amount of plural forms for different languages in one format: `singular | plural` for English or `singular | few | plural` for Russian for example.

And then just `pluralize('key', value, Vue.config.lang)` as a function in JS

And `{{ $t('key') | pluralize(computedProperty()) }}` as a filter in templates:

``` html
<!-- module.vue -->
<script>
    import filters from './filters'
    export default {
        filters: filters,
        …
    }
</script>
```

``` js
// filters.js
import Vue from 'vue'
import pluralize from './modules/pluralize'
export default {
    pluralize: function(string, amount) {
        return pluralize(string, amount, Vue.config.lang)
    }
}
```

Other sources you can see in [this repo](https://github.com/Grawl/jew-simulator/).

### PR DESCRIPTION
**Pull request by Raiondesu**
Allows custom pluralization handlers via prototype modification.

This is achieved by moving fetchChoice and getChoiceIndex functions directly into VueI18n prototype without any implementation changes. This ensures full backward-compatibility while also providing a possibility for extension to fit specific needs of specific users.

Very simplified example using rules for Slavic langauges (Russian, Ukrainian, etc.):
```js
/**
 * @param choice {number} a choice index given by the input to $tc: `$tc('path.to.rule', choiceIndex)`
 * @param choiceLength {number} an overall amount of available choices
 * @returns a final choice index to select plural word by
**/
VueI18n.prototype.getChoiceIndex = function (choice, choicesLength) {
  // this === VueI18n instance, so the locale property exists
  if (this.locale !== 'ru') {
    // proceed to the default implementation
  }

  if (choice === 0) {
    return 0;
  }

  const teen = choice > 10 && choice < 20;
  const endsWithOne = choice % 10 === 1;

  if (!teen && endsWithOne) {
    return 1;
  }
  if (!teen && choice % 10 >= 2 && choice % 10 <= 4) {
    return 2;
  }
  return (choicesLength < 4) ? 2 : 3;
}
```
 This would effectively allow this:
 ```javascript
const messages = {
  ru: {
    car: '0 машин | 1 машина | {n} машины | {n} машин',
    banana: 'нет бананов | 1 банан | {n} банана | {n} бананов'
  }
}
```
Where the format is `0 things | 1 thing | few things | multiple things`.

Then:
 ```html
<p>{{ $tc('car', 1) }}</p>
<p>{{ $tc('car', 2) }}</p>
<p>{{ $tc('car', 4) }}</p>
<p>{{ $tc('car', 12) }}</p>
<p>{{ $tc('car', 21) }}</p>
 <p>{{ $tc('car', 0) }}</p>
<p>{{ $tc('car', 4) }}</p>
<p>{{ $tc('car', 11) }}</p>
<p>{{ $tc('car', 31) }}</p>
```
 Which results in:
 ```html
<p>1 машина</p>
<p>2 машины</p>
<p>4 машины</p>
<p>12 машин</p>
<p>21 машина</p>
 <p>нет бананов</p>
<p>4 банана</p>
<p>11 бананов</p>
<p>31 банан</p>
```

Pretty much closes #78.

### CODE REVIEW

**Comment by Raiondesu** [comment]
The feature is already working in production installed from my fork repo.

**Comment by Raiondesu** [comment]
Yay! I think many people would love to see this on npm. ^_^

**Comment by mitar** [comment]
Should we have some shared code for a function which supports various languages?

**Comment by Raiondesu** [comment]
@mitar, I personally think this can be left to particular implementations of "getChoiceIndex". Also, many languages do not share any pluralization rules, so there is no need to build this in the lib itself - too many edge-cases to handle.
All the general code is already generalized.

**Comment by mitar** [comment]
Hm, this [document seems to be able to provide quite extensive list of those formulas](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html), so I just wonder why we could not simply have it in code we all use.

**Comment by Raiondesu** [comment]
Because this would add unnecessary load (for most cases), increasing the size of the default code base. If I use only Russian and English in my project - why would I want to also have specific rules for Arabic and German?

This is why it's better to just define these rules yourself whenever you need them by overloading getChoiceIndex.

@kazupon plans to integrate the ICU formatting, which would allow for declarative definitions for those rules, making them so much easier to describe.

**Comment by AndrewBogdanovTSS** [comment]
@Raiondesu is there any chance to improve override for this function so it can be available from options? Could you look into my [feature request](https://github.com/kazupon/vue-i18n/issues/464)? Thanks!

**Comment by Raiondesu** [comment]
@AndrewBogdanovTSS, well, this is possible...

**Comment by kwolniak** [comment]
Hello.

Could you please help me and tell how can I use it in nuxt app? I have all i18n config in nuxt.config.js.

**Comment by AndrewBogdanovTSS** [comment]
@kwolniak https://kazupon.github.io/vue-i18n/guide/pluralization.html

**Pull request merged**
