### PR TITLE
Put dash at the end of character class in example i18n.js code.

### PR DESCRIPTION
**Pull request by jlebar**
The regexp /[0-9-_]/ matches digits, hyphen, and underscore, but only
because the hyphen comes right after a hyphenated range.  If you put
anything in between the 9 and the hyphen, boom.  It's so surprising, I
think it's clearer just to put the hyphen at the end.

### CODE REVIEW

**Comment by kazupon** [comment]
@jlebar 
Thank you for your PR!
I've just changed branch to `v8.x` from `dev` because of `dev` branch is development branch of `vue-i18n-next`.
However, this PR is conflicting now.

Could you fix the conflict, please? 🙏

**Comment by jlebar** [comment]
Somehow when the branch was changed, other commits were pulled in; I think that's what caused the conflict?  I just cherry-picked this onto the v8.x branch and then force-pushed here, lmk if this looks OK.

Should I create another patch against `dev`?

Thank you for the plugin (and the welcoming community!).

**Comment by jlebar** [comment]
Actually, I found another issue, namely that the regexp is not anchored, so (as I read https://www.npmjs.com/package/require-context), it isn't looking for files which *end* in ".json", just any file which contains ".json".

Would you like that as a separate PR, or in here?

**Comment by kazupon** [comment]
>Would you like that as a separate PR, or in here

I hope that you will continue to commit to this PR. :)

**Comment by jlebar** [comment]
OK, have to go to sleep now, but I'll try to put it together tomorrow morning!

**Comment by jlebar** [comment]
Pushed the other change, please have a look!

**Comment by kazupon** [comment]
Thanks!

**Pull request merged**
