### PR TITLE
feat: add a new option fallbackRootWithEmptyString

### PR DESCRIPTION
**Pull request by PeterAlfredLee**
This PR introduces a new option `fallbackRootWithEmptyString`. This option decides a i18n message should fallback to root or not if it's a empty string.

Currently, the fallback root check logic is like this:
```javascript
 !val && !isNull(this._root) && this._fallbackRoot
```

This means that: in the case that the `val` is an empty string(''), it will also fallback to root. This implementation is different from the one in version 9.x(in i18n 9.x, the empty string will not trigger fallback root). Besides that, this implementation may make it difficult if the user want to bypass the fallback operations of some value.

This PR introduces a new option `fallbackRootWithEmptyString` whose default value is `true`. It means the default logic of fallback root is still like this :
```javascript
 !val && !isNull(this._root) && this._fallbackRoot
```
This means the PR is **not** a breaking change: by default, the fallback root logic will work in the existing logic.

When setting the `fallbackRootWithEmptyString` to be `false`m the fallback root logic will become like this:
```javascript
isNull(val) && !isNull(this._root) && this._fallbackRoot
```
This means the emptr string('') will not trigger fallback root.

Besides that, I didn't add this option in the `api.md`, cause I want to hear your ideas about this new option first.  :) @kazupon

### CODE REVIEW

**Review by kazupon — COMMENTED** [review]
Oh, I have not realized I was having a BREAKING CHANGE in v9 😣
This option should be useful when migrating from v8 to v9 for some users.
This should be documented in the API docs (api.md).

And we need to add the typescript type definition as well.
https://github.com/kazupon/vue-i18n/blob/v8.x/types/index.d.ts

**Comment by PeterAlfredLee** [comment]
> Oh, I have not realized I was having a BREAKING CHANGE in v9 😣 This option should be useful when migrating from v8 to v9 for some users. This should be documented in the API docs (api.md).
> 
> And we need to add the typescript type definition as well. https://github.com/kazupon/vue-i18n/blob/v8.x/types/index.d.ts

Sure. I will add this in `api.md` and `index.d.ts`.

**Comment by PeterAlfredLee** [comment]
> > Oh, I have not realized I was having a BREAKING CHANGE in v9 persevere This option should be useful when migrating from v8 to v9 for some users. This should be documented in the API docs (api.md).
> > And we need to add the typescript type definition as well. https://github.com/kazupon/vue-i18n/blob/v8.x/types/index.d.ts
> 
> Sure. I will add this in `api.md` and `index.d.ts`.

I added this in `api.md`, `api/README.md` and `index.d.ts`.
I also added the tag `:new: 8.26+` in the `api.md` and `api/README.md`, but I'm not sure if the `8.26+` description is right or not. Please feel free to tell me if this need to be modified.

PS: Please note that the added description in `ru/api/README.md` and `pt/api/README.md` are translated by Google translate.

PPS: And I didn't regenerate the docs cause IMO docs should only be regenerated before a new release.

**Review by kazupon — APPROVED** [review]
OK! Thanks!
It looks good to me! :)

**Pull request merged**
