### PR TITLE
Skip non-element VNode in interpolation

### LINKED ISSUE #210: i18n component parses line break as a VNode
### vue & vue-i18n version
vue: 2.4.2
vue-i18n: 7.1.1

### Reproduction Link

https://jsbin.com/hohalimepo/edit?html,js,output

### What is Expected?
Both should render correct sentence.

### What is actually happening?
The first one parses line break as a VNode

```html
<i18n path="msg" tag="div">
  <strong>bold</strong>
  <em>italic</em>
</i18n>
```
image

So that the second slot in i18n string was replaced with the `TextNode`, which was the line break between two child elements.

image

I have to now write it like this.

```html
<i18n path="msg" tag="div">
  <strong>bold</strong><em>italic</em>
</i18n>
```
image

I'm not sure whether this should be dealt with by vdom or by i18n lib, I prefer the latter. Nonetheless, for this particular functional component, I think only element nodes (`nodeType === 1`) should be considered. Since plain text can be easily moved to i18n message object.

### PR DESCRIPTION
**Pull request by myst729**
Please visit https://github.com/kazupon/vue-i18n/issues/210 for the details.

fix #210

### CODE REVIEW

**Comment by myst729** [comment]
Yes, I also noticed that unit tests fail. And I thought again, this is a bit complicated.

As addressed in #210 , line breaks are considered as VNodes. Follow code produces 3 VNodes: two elements and the line break in between.

```html
<i18n path="msg" tag="div">
  <strong>bold</strong>
  <em>italic</em>
</i18n>
```

However, following code has exactly the same VNodes parsed: the whitespace is a VNode too.

```html
<i18n path="msg" tag="div">
  <strong>bold</strong> <em>italic</em>
</i18n>
```

I think what VDom done is right, because it behaves similar as how browsers parse line breaks or contiguous whitespaces between elements. So the question shifts here: **are the text nodes inside `<i18n>` meaningful, or not?**

Before component interpolation this is very simple. All text interpolations are passed within an object to the `$t` method. The user has full control of them, so they're **all** meaningful.

But for component interpolation, it's not easy to answer. And current test cases are only designed for **meaningful** text, e.g. data binding.

So my current approach is to check both `tag` and `text` of the VNode:

```js
if (child.tag || child.text.trim()) {
  params.push(child)
}
```

This will skip all text content that consists of white spaces (general, not only  `%20`).

Then the last question remains: as of `i18n` component, shall we give full control of text content back to the user? For, example, some sort of an `i18n-text` child component (which is absolutely not elegant).

I haven't had a conclusion yet.

**Comment by myst729** [comment]
Maybe another approach is to add a mandatory slot key, e.g.:

```js
messages: {
  en: {
    msg: 'This is {0} and {1}.'
  }
}
```

```js
<i18n path="msg" tag="div">
  <strong slot="0">bold</strong>
  <em slot="1">italic</em>
</i18n>
```

To work with mixed content, we could:

```js
<i18n path="msg" tag="div" :slots="{'1': 'place text'}">
  <strong slot="0">bold</strong>
</i18n>
```

This way, you can even make the i18n strings more readable, e.g.:

```js
messages: {
  en: {
    msg: 'This is {boldText}, and this is {plainText}.'
  }
}
```

```js
<i18n path="msg" tag="div" :slots="{plainText: 'place text'}">
  <strong slot="boldText">bold text</strong>
</i18n>
```

**Comment by myst729** [comment]
As I dig deeper into the source code, I found another issue that may be a barrier of implementing the `places` approach I mentioned above. The list formatting is implemented individually with named formatting.

> [vue-i18n] Type of token 'list' and format of value 'named' don't match!

For messages interpolated with "numbers":
```js
messages: {
  en: {
    msg: 'This is {0} and {1}.'
  }
}
```

I could only pass an array: 

```html
<div>{{ $t('msg', ['bold', 'italic']) }}</div>
```

If I pass an object:
```html
<div>{{ $t('msg', {'0': 'bold', '1': 'italic'}) }}</div>
```
The warning message appears, which is fine. However, the translation stops there. This is a bit too strict to the users. And it doesn't behave consistent with JavaScript.

```js
// These two expressions output the same result
Object.keys(['bold', 'italic'])
Object.keys({'0': 'bold', '1': 'italic'})
```

I've read some other i18n libs or components before, e.g. Dojo, Angular, etc. Under the hood, they all make list formatting syntax sugar of named formatting. To the users, this brings flexibility of formatting messages interpolated with "numbers". To the developers, reuse of such mechanism could be a lot easier to ship features like the "places" idea I proposed.

**Comment by kazupon** [comment]
Thank you for your fix and consideration!

>So the question shifts here: are the text nodes inside <i18n> meaningful, or not?

Sorry, my poor documentation. 🙇 
In currently, text nodes inside `<i18n>` not meaningful due to assumed the use of the html tag expansion.
In about text nodes, I had not thought about it so much. 😅 

 >shall we give full control of text content back to the user?

In about this, I don't know it, due to cannot imagine use-case. 💭❓ 
if we'll support it, I prefer `place` special attribute.

>The list formatting is implemented individually with named formatting.
>they all make list formatting syntax sugar of named formatting. To the users, this brings flexibility of formatting messages interpolated with "numbers". 

Oh! 💡That's good idea!
However, That improvement is big affecting to vue-i18n codes.
I'd like to improve it in next major release.

**Comment by myst729** [comment]
> In currently, text nodes inside `<i18n>` not meaningful due to assumed the use of the html tag expansion.

If plain text is not under consideration, then I guess this PR is compatible with the design purpose.

> In about this, I don't know it, due to cannot imagine use-case. 💭❓

`<i18n>` is designed for the use cases of html interpolations, I see it a perfect solution for #75 (which, yes, was opened by me 😅). So let's rewrite the demo code in that issue with `<i18n>`:

```js
const locales = {
  en: {
    info: 'You can {0} until 30 minutes from departure.',
    refund: 'refund the ticket',
    change: 'change your flight'
  },
  cn: {
    info: '办理{0}手续的截止时间为起飞前 30 分钟。',
    refund: '退票'
    change: '改签'
  }
}
```
```html
<i18n path="info" tag="p">
  <a href="http://example.com">{{ $t('refund') }}</a>
</i18n>
```

Changing the refund link is not a matter of message string any longer. Also, I can now make it just plain text, if the online service is not available yet. Whether the service is available is not a matter of message string either. Plus I could define more actions at ease. So this is really great!

Let's go one step further. Say, for different actions the time limit vary. How do we do?

```js
const locales = {
  en: {
    info: 'You can {0} until {1} minutes from departure.',
    refund: 'refund the ticket',
    change: 'change your flight'
  },
  cn: {
    info: '办理{0}手续的截止时间为起飞前 {1} 分钟。',
    refund: '退票',
    change: '改签'
  }
}
```
```html
<i18n path="info" tag="p">
  <a href="http://example.com">{{ $t('change') }}</a>
  15
</i18n>
```

Or maybe better:

```js
data: {
  limit: {
    refund: 30,
    change: 15
  }
}
```

```html
<i18n path="info" tag="p">
  <a href="http://example.com">{{ $t('change') }}</a>
  {{ limit.change }}
</i18n>
```

Mixed content interpolations of element and plain text. But this has a tricky pitfall, what if the user wants to pass an empty string in his use case? How do we know it's by intention, or just another line break? We really couldn't.

> if we'll support it, I prefer place special attribute.

With `place/places`, this could be:

```html
<i18n path="info" tag="p" :places="{'1': limit.change}">
  <a place="0" href="http://example.com">{{ $t('change') }}</a>
</i18n>
```

If we force the use of `places` for plain text, then dealing with text nodes in `<i18n>` could be so easy - just ignore them! Since this component is designed for element interpolations in the beginning.

> However, That improvement is big affecting to vue-i18n codes.
> I'd like to improve it in next major release.

I agree. It's a big architectural change. It does have necessity of thinking twice before move.

**Comment by kazupon** [comment]
Thank you for detailed explanation!

I could understand about use-cases!
So, we would like to support it.

Could you implement it please?

If you can not implement, I hope you open the issues about that specification as docs. In this case, I merge this PR, after that I sometime implement it.

**Comment by myst729** [comment]
It may not be very soon, but yep, I'll be glad to involve.

**Comment by kazupon** [comment]
Thank you for your issue registering!
Okay, then I'll merge your PR.

**Pull request merged**
