### PR TITLE
Allow component interpolation without root element

### LINKED ISSUE #876: Can't create component interpolation without a root element / tag
It's currently not possible to create a [component interpolation](https://kazupon.github.io/vue-i18n/guide/interpolation.html) without creating a root element. I.e. generated output is for example of the form:
```html
<root node, by default span>
   Text node
   <child element />
</root node>
```
but can not be just
```html
Text node
<child element />
```
without the root element.

This is because this line here enforces a tag:
https://github.com/kazupon/vue-i18n/blob/bd3a0324851fa6667f0e02a8008474fd528d429a/src/components/interpolation.js#L42
The next line then never uses the `else` case.

### PR DESCRIPTION
**Pull request by danimoh**
Component interpolation without a root element can now be enabled
by setting the tag prop to false.
Let me know if you prefer something else then value `false`, for example
a keyword like `"none"`.
Value false would need to be specified as `:tag="false"`, a keyword as
`tag="none"` which might read a little nicer.

Fixes #876

### CODE REVIEW

**Comment by kazupon** [comment]
Thank you for your PR!
This fix is ​​an enhancement, but we need to keep backward compatible.

`<i18n>` component `tag` prop is currently string type only. 
https://kazupon.github.io/vue-i18n/api/#i18n-functional-component

My recommendation is that backwards compatibility can be maintained by also supporting boolean types.  when passed  boolean value (`false` or 'true`), returning children.
If `tag` prop is nothing, it should be `span`.

The same goes for `<i18n>` component.

**Comment by danimoh** [comment]
That makes sense.
What would a value of `true` stand for though?
Should the default be used for `true` which is a `span`?

Would you want to work on the additional changes to the documentation, `i18n-n` and support for `true` yourself?
That would likely be faster then me trying to figure it out.
But if you want, I can help of course.

**Comment by kazupon** [comment]
> What would a value of `true` stand for though?

if `tag` prop value is `true`, it should be `span`, else `false` value, it should be returned children.

> Should the default be used for `true` which is a `span`?

if `tag` prop is nothing, it should be `true` same.

>Would you want to work on the additional changes to the documentation, i18n-n and support for true yourself?

I'm busy developing for vue-i18n-next, so I'm glad if you could help. 🙏

**Comment by danimoh** [comment]
I changed the behavior for `true` as discussed and added support for `i18n-n` components without root element.
I also added tests and documentation for this feature.
I hope I built the docs correctly, please have a look.

**Pull request merged**
