### PR TITLE
fix: number format keys missing compared the Intl.Number object

### PR DESCRIPTION
**Pull request by jevillard**
Suggested fix for #1047

### CODE REVIEW

**Comment by jevillard** [comment]
Hello @kazupon,

I don't understand why the e2e tests were not successful because the problem seems to be related to a session or Chrome driver error...
https://app.circleci.com/pipelines/github/kazupon/vue-i18n/379/workflows/f089ce4c-1fdf-409d-a5d5-3a7484901686/jobs/1614


Do you have an idea? Thanks :smiley:

**Comment by jevillard** [comment]
Reopen the PR after adding the documentation

**Comment by kazupon** [comment]
@jevillard 
Thank you for your PR!

In about e2e, We can resolve this issue, when we update `chromedriver@86.0.0`.
https://github.com/kazupon/vue-i18n/blob/6ace404f7dd9937dc05cabe14164abb750856a2b/package.json#L39

**Comment by jevillard** [comment]
@kazupon 
Thank you for your reply! I fix it.

**Pull request merged**
